---
- name: Install Python and pip
  package:
    name: "{{ python_packages[ansible_os_family] }}"
    state: present
  become: "{{ ansible_os_family == 'Debian' }}"

- name: Install pyenv for version management
  git:
    repo: https://github.com/pyenv/pyenv.git
    dest: "{{ ansible_env.HOME }}/.pyenv"
    
- name: Install pipx for CLI tools
  pip:
    name: pipx
    state: present
    extra_args: --user

- name: Ensure pipx is in PATH
  lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    line: 'export PATH="$HOME/.local/bin:$PATH"'
    create: yes
