---
- name: Install common packages
  package:
    name: "{{ common_packages[ansible_os_family] }}"
    state: present
  become: "{{ ansible_os_family == 'Debian' }}"

- name: Install Homebrew (macOS)
  shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  args:
    creates: /opt/homebrew/bin/brew
  when: ansible_os_family == "Darwin"
